// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages_edit.sql

package db

import (
	"context"
)

const countMessagesAfter = `-- name: CountMessagesAfter :one
SELECT COUNT(*) as count
FROM messages m1
WHERE m1.session_id = ?
AND m1.created_at > (SELECT m2.created_at FROM messages m2 WHERE m2.id = ?)
`

type CountMessagesAfterParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) CountMessagesAfter(ctx context.Context, arg CountMessagesAfterParams) (int64, error) {
	row := q.queryRow(ctx, q.countMessagesAfterStmt, countMessagesAfter, arg.SessionID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM messages
WHERE id = ?
`

func (q *Queries) DeleteMessageByID(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageByIDStmt, deleteMessageByID, id)
	return err
}

const deleteMessagesAfter = `-- name: DeleteMessagesAfter :exec
DELETE FROM messages
WHERE id IN (
    SELECT m1.id
    FROM messages m1
    WHERE m1.session_id = ?
    AND m1.created_at > (SELECT m2.created_at FROM messages m2 WHERE m2.id = ?)
)
`

type DeleteMessagesAfterParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) DeleteMessagesAfter(ctx context.Context, arg DeleteMessagesAfterParams) error {
	_, err := q.exec(ctx, q.deleteMessagesAfterStmt, deleteMessagesAfter, arg.SessionID, arg.ID)
	return err
}

const getMessagesAfter = `-- name: GetMessagesAfter :many
SELECT m1.id, m1.session_id, m1.role, m1.parts, m1.model, m1.created_at, m1.updated_at, m1.finished_at, m1.provider, m1.is_summary_message
FROM messages m1
WHERE m1.session_id = ?
AND m1.created_at > (SELECT m2.created_at FROM messages m2 WHERE m2.id = ?)
ORDER BY m1.created_at ASC
`

type GetMessagesAfterParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetMessagesAfter(ctx context.Context, arg GetMessagesAfterParams) ([]Message, error) {
	rows, err := q.query(ctx, q.getMessagesAfterStmt, getMessagesAfter, arg.SessionID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMessages = `-- name: GetUserMessages :many
SELECT id, session_id, role, parts, model, created_at, updated_at, finished_at, provider, is_summary_message
FROM messages
WHERE session_id = ?
AND role = 'user'
ORDER BY created_at DESC
`

func (q *Queries) GetUserMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.getUserMessagesStmt, getUserMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
			&i.IsSummaryMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
