// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prompt_history.sql

package db

import (
	"context"
)

const addPromptHistory = `-- name: AddPromptHistory :one
INSERT INTO prompt_history (
    id,
    prompt,
    created_at
) VALUES (
    ?,
    ?,
    strftime('%s', 'now')
)
ON CONFLICT(prompt) DO UPDATE SET
    created_at = strftime('%s', 'now')
RETURNING id, prompt, created_at
`

type AddPromptHistoryParams struct {
	ID     string `json:"id"`
	Prompt string `json:"prompt"`
}

func (q *Queries) AddPromptHistory(ctx context.Context, arg AddPromptHistoryParams) (PromptHistory, error) {
	row := q.queryRow(ctx, q.addPromptHistoryStmt, addPromptHistory, arg.ID, arg.Prompt)
	var i PromptHistory
	err := row.Scan(&i.ID, &i.Prompt, &i.CreatedAt)
	return i, err
}

const clearPromptHistory = `-- name: ClearPromptHistory :exec
DELETE FROM prompt_history
`

func (q *Queries) ClearPromptHistory(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearPromptHistoryStmt, clearPromptHistory)
	return err
}

const getPromptByID = `-- name: GetPromptByID :one
SELECT id, prompt, created_at
FROM prompt_history
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPromptByID(ctx context.Context, id string) (PromptHistory, error) {
	row := q.queryRow(ctx, q.getPromptByIDStmt, getPromptByID, id)
	var i PromptHistory
	err := row.Scan(&i.ID, &i.Prompt, &i.CreatedAt)
	return i, err
}

const getPromptHistoryCount = `-- name: GetPromptHistoryCount :one
SELECT COUNT(*) as count
FROM prompt_history
`

func (q *Queries) GetPromptHistoryCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getPromptHistoryCountStmt, getPromptHistoryCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPromptHistory = `-- name: ListPromptHistory :many
SELECT id, prompt, created_at
FROM prompt_history
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListPromptHistory(ctx context.Context, limit int64) ([]PromptHistory, error) {
	rows, err := q.query(ctx, q.listPromptHistoryStmt, listPromptHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptHistory{}
	for rows.Next() {
		var i PromptHistory
		if err := rows.Scan(&i.ID, &i.Prompt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
