// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    id,
    session_id,
    content,
    active_form,
    status,
    position,
    created_at,
    updated_at,
    completed_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now') * 1000,
    strftime('%s', 'now') * 1000,
    NULL
) RETURNING id, session_id, content, active_form, status, position, created_at, updated_at, completed_at
`

type CreateTodoParams struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	Content    string `json:"content"`
	ActiveForm string `json:"active_form"`
	Status     string `json:"status"`
	Position   int64  `json:"position"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.queryRow(ctx, q.createTodoStmt, createTodo,
		arg.ID,
		arg.SessionID,
		arg.Content,
		arg.ActiveForm,
		arg.Status,
		arg.Position,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ActiveForm,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteTodoStmt, deleteTodo, id)
	return err
}

const deleteTodosBySession = `-- name: DeleteTodosBySession :exec
DELETE FROM todos
WHERE session_id = ?
`

func (q *Queries) DeleteTodosBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteTodosBySessionStmt, deleteTodosBySession, sessionID)
	return err
}

const getMaxTodoPosition = `-- name: GetMaxTodoPosition :one
SELECT COALESCE(MAX(position), -1) as max_position
FROM todos
WHERE session_id = ?
`

func (q *Queries) GetMaxTodoPosition(ctx context.Context, sessionID string) (interface{}, error) {
	row := q.queryRow(ctx, q.getMaxTodoPositionStmt, getMaxTodoPosition, sessionID)
	var max_position interface{}
	err := row.Scan(&max_position)
	return max_position, err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, session_id, content, active_form, status, position, created_at, updated_at, completed_at
FROM todos
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTodoByID(ctx context.Context, id string) (Todo, error) {
	row := q.queryRow(ctx, q.getTodoByIDStmt, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ActiveForm,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listTodosBySession = `-- name: ListTodosBySession :many
SELECT id, session_id, content, active_form, status, position, created_at, updated_at, completed_at
FROM todos
WHERE session_id = ?
ORDER BY position ASC
`

func (q *Queries) ListTodosBySession(ctx context.Context, sessionID string) ([]Todo, error) {
	rows, err := q.query(ctx, q.listTodosBySessionStmt, listTodosBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Content,
			&i.ActiveForm,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoContent = `-- name: UpdateTodoContent :one
UPDATE todos
SET
    content = ?,
    active_form = ?
WHERE id = ?
RETURNING id, session_id, content, active_form, status, position, created_at, updated_at, completed_at
`

type UpdateTodoContentParams struct {
	Content    string `json:"content"`
	ActiveForm string `json:"active_form"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateTodoContent(ctx context.Context, arg UpdateTodoContentParams) (Todo, error) {
	row := q.queryRow(ctx, q.updateTodoContentStmt, updateTodoContent, arg.Content, arg.ActiveForm, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ActiveForm,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateTodoPosition = `-- name: UpdateTodoPosition :exec
UPDATE todos
SET position = ?
WHERE id = ?
`

type UpdateTodoPositionParams struct {
	Position int64  `json:"position"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateTodoPosition(ctx context.Context, arg UpdateTodoPositionParams) error {
	_, err := q.exec(ctx, q.updateTodoPositionStmt, updateTodoPosition, arg.Position, arg.ID)
	return err
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
UPDATE todos
SET
    status = ?,
    completed_at = CASE
        WHEN ? = 'completed' AND completed_at IS NULL THEN strftime('%s', 'now') * 1000
        WHEN ? != 'completed' THEN NULL
        ELSE completed_at
    END
WHERE id = ?
RETURNING id, session_id, content, active_form, status, position, created_at, updated_at, completed_at
`

type UpdateTodoStatusParams struct {
	Status  string      `json:"status"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	ID      string      `json:"id"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.queryRow(ctx, q.updateTodoStatusStmt, updateTodoStatus,
		arg.Status,
		arg.Column2,
		arg.Column3,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Content,
		&i.ActiveForm,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
